// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_n7xBoX9vHSuOZVGztoolUuKWAbdKaIM',
    appId: '1:377165231790:web:2727fdead53157dd6e1f3f',
    messagingSenderId: '377165231790',
    projectId: 'setupios',
    authDomain: 'setupios.firebaseapp.com',
    storageBucket: 'setupios.appspot.com',
    measurementId: 'G-2C2YQEZH3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPeVgnIg43IPGB-Jyhpt6SbAQ03LWvJCA',
    appId: '1:377165231790:android:bf50384e314bcd8a6e1f3f',
    messagingSenderId: '377165231790',
    projectId: 'setupios',
    storageBucket: 'setupios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI8vYi8pTGYLvZa3mT-28KA3kWqdoIFQc',
    appId: '1:377165231790:ios:cdc81daee2fc4b936e1f3f',
    messagingSenderId: '377165231790',
    projectId: 'setupios',
    storageBucket: 'setupios.appspot.com',
    iosClientId: '377165231790-i6kejvvu0vaumoh92eigqo1scjceo6c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.knm',
  );
}
